name: pycequeau
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=3.0.2
  - python=3.7
  - pyproj
  - xarray
  - pytest
  - scipy
  - autopep8
  - matplotlib
  - ipykernel
  - geopandas
  - rasterstats
  - netcdf4
  - shapely
