name: pycequeau
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - affine=2.3.0
  - alabaster=0.7.12
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - cftime=1.5.1.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - cryptography=39.0.1
  - curl=8.2.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - entrypoints=0.4
  - expat=2.5.0
  - fftw=3.3.9
  - fiona=1.8.22
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=1.0.6
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - jupyterlab_pygments=0.1.2
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.2.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libgdal=3.0.2
  - libiconv=1.16
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzip=1.8.0
  - lz4-c=1.9.4
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - nbconvert=6.4.4
  - nbformat=5.7.0
  - nbsphinx=0.9.3
  - nbsphinx-link=1.3.0
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - networkx=2.6.3
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.3.5
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - pluggy=1.0.0
  - ply=3.11
  - proj=6.2.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - py=1.11.0
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=2.6.1.post1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.7.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pywin32=305
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - rasterio=1.2.10
  - rasterstats=0.14.0
  - requests=2.28.1
  - rtree=1.0.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.6.3
  - shapely=1.8.4
  - simplejson=3.17.6
  - sip=6.6.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sphinx-copybutton=0.5.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - sqlite=3.41.2
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tiledb=2.3.3
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xarray=0.20.1
  - xerces-c=3.2.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - async-generator==1.10
      - gdal==3.0.2
      - jinja2==3.0.3
      - jupyter-core==4.12.0
      - matplotlib-scalebar==0.8.1
      - natsort==8.4.0
      - nbclient==0.5.0
      - pygments==2.16.1
      - sphinx==5.3.0
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-jquery==4.1
