name: pycequeau
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - python=3.7
  - pyproj
  - xarray
  - scipy
  - autopep8
  - matplotlib
  - ipykernel
  - geopandas
  - rasterstats
  - netcdf4
  - shapely
